/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef CSCMIB_H
#define CSCMIB_H

/*
 * function declarations 
 */
void            init_cscMIB(void);
Netsnmp_Node_Handler handle_cogentBytes;
Netsnmp_Node_Handler handle_orionBytes;
Netsnmp_Node_Handler handle_campusBytes;

#endif                          /* CSCMIB_H */
