#!/bin/bash

# This file updates the orion routing table.
# Put it at /usr/local/sbin/update-orion-routes.

wget --quiet -O - https://istns.uwaterloo.ca/borderroutes/borderroutes.txt | /usr/local/sbin/orionroutes.py
